### ISSUE TITLE
Error at launch: "Use of const in strict mode."

### ISSUE THREAD

**Issue by CoderNinja** [AelithBlanchett/fchatlib#4]
In libfchat.js, line 4, when launching the Example Plugin Bot

const throttle = require('throttle-function');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (Documents\FChatBot-ExamplePlugin-master\app.js:2:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by CoderNinja** [comment]
My stupidity, actually. I updated to a newer version of node, though I thought I had already updated, and it seems to be running fine.
